USE master
GO
IF EXISTS (SELECT * FROM sysdatabases WHERE NAME='CONTRACTORS_ORDERS')
		DROP DATABASE CONTRACTORS_ORDERS
GO
CREATE DATABASE "CONTRACTORS_ORDERS"
GO
use "CONTRACTORS_ORDERS"
GO
IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id('dbo.ORDER') and sysstat & 0xf = 3)
	drop table "dbo"."Order"
GO
IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id('dbo.CONTRACTOR') and sysstat & 0xf = 3)
	drop table "dbo"."Contractor"
GO
CREATE TABLE "Contractor"(
	"ID_KONTRAHENTA" "int" IDENTITY (1, 1) NOT NULL ,
	"NAZWA" varchar (100),
	"NIP" varchar (30),
	"DATA_DODANIA" datetime2,
	CONSTRAINT "PK_KONTRAHENCI" PRIMARY KEY CLUSTERED ("ID_KONTRAHENTA")
	)
GO
CREATE TABLE "Order"(
	"ID_ZAMOWIENIA" int IDENTITY (1, 1) NOT NULL,
	"ID_KONTRAHENTA" int,
	"NUMER" varchar (30),
	"DATA_DODANIA" datetime2,
	CONSTRAINT "PK_ZAMOWIENIA" PRIMARY KEY CLUSTERED ("ID_ZAMOWIENIA"),
	CONSTRAINT "FK_KONTRAHENT" FOREIGN KEY ("ID_KONTRAHENTA") REFERENCES "dbo"."Contractor" ("ID_KONTRAHENTA")
)